module Api
  module V1
    class ClientProfilesController < ApplicationController
      def create
        @client_profile = ClientProfile.new(client_profile_params)
        @client_profile.user = current_user

        if @client_profile.save

          @diet_plan = DietPlan.new(title: 'The Ultimate Diet', description: 'recommended for you!', end_date: @client_profile[:target_date], notes: 'Start taking steps in your fitness journey.')
          @diet_plan.user = current_user
          @diet_plan.save

          n = 14
          @compute_bmi = @client_profile[:current_weight].to_f / (@client_profile[:height].to_f * 0.01)**2

          while n.positive?
            if @compute_bmi < 16 || @compute_bmi > 40
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED',name: 'Corned Beef Breakfast Biscuits', media: 'https://www.edamam.com/web-img/4c5/4c5faca6ea3e09900c42f5b298a49ba1.jpg', calories: 2335, totalWeight: 985, ingredientLines: '["12 ounces Flakey biscuit dough ; - one can","2 tablespoon Oil","12 ounces Corned beef, canned ; - one can","1/2 cup Onion ; - chopped fine","2 cloves Garlic ; - finely diced","1 cup Shredded potatoes ; - frozen hash browns","1/2 teaspoon Black pepper ; - to taste","2 tablespoons ketchup ; - Garmish"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["12 ounces Flakey biscuit dough ; - one can","2 tablespoon Oil","12 ounces Corned beef, canned ; - one can","1/2 cup Onion ; - chopped fine","2 cloves Garlic ; - finely diced","1 cup Shredded potatoes ; - frozen hash browns","1/2 teaspoon Black pepper ; - to taste","2 tablespoons ketchup ; - Garmish"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Asian Roasted Brussels Sprouts with Cranberries recipes', media: 'https://www.edamam.com/food-img/07e/07e106ab3536d57428e5c46d009038f8.jpg', calories: 655, totalWeight: 625, ingredientLines: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Coca-Cola–Glazed Chicken Wings', media: 'https://www.edamam.com/web-img/b87/b879d16aa42cee3b6b5df49d853c57c0.jpg', calories: 2632.7, totalWeight: 1427, ingredientLines: '["1 cup Coca-Cola Classic","Juice of 2 limes","1 1/2 cups firmly packed light brown sugar","3 jalapeño chiles, finely chopped, plus 2 jalapeño chiles, sliced, for garnish","3 lbs. chicken wings (12–14 whole wings)","Coarse salt and freshly ground black pepper"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band close-grip push-up', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0975.gif', target: 'triceps', workout_id: 975, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: '3/4 sit-up', status: 'NOT STARTED', bodyPart: 'waist', equipment: 'body weight', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0001.gif', target: 'abs', workout_id: 1, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'deep push up', status: 'NOT STARTED', bodyPart: 'chest', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1274.gif', target: 'pectorals', workout_id: 1274, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            elsif @compute_bmi == 16 || @compute_bmi < 18.4
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Philly Cheesesteak Chex Mix', media: '', calories: 2070, totalWeight: 764, ingredientLines: '["5 cups Wheat Chex® cereal","1 container (6 oz) French-fried onions","1/2 cup cubed provolone cheese","2 packages (3.25 oz each) beef jerky nuggets, cut in half","2 tablespoons cheese powder"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Luby\'s Macaroni and Cheese', media: 'https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg', calories: 1225, totalWeight: 616, ingredientLines: '["2 c dry elbow macaroni","2 Tbsp nonfat dry milk","2 Tbsp all pourpose flour","1 Tbsp butter or margarine, melted","1 1/4 c boiling water","3 c shredded yellow american cheese from the deli","1/4 tsp salt"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Oven-Barbecued Chicken Wings', media: 'https://www.edamam.com/web-img/17f/17f22fc6b71117b3b8dc447a364671f8.jpg', calories: 1250.7, totalWeight: 626, ingredientLines: '["12 whole chicken wings","½ cup honey","3 tablespoons Worcestershire sauce","4 tablespoons soy sauce","2 tablespoons prepared mustard or 1 tablespoon dry mustard","2 tablespoons red wine or cider vinegar"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band alternating biceps curl', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0968.gif', target: 'biceps', workout_id: 968, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'ankle circles', status: 'NOT STARTED', bodyPart: 'lower legs', equipment: 'body weight', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1368.gif', target: 'calves', workout_id: 1368, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate biceps curl', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0285.gif', target: 'biceps', workout_id: 285, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            elsif @compute_bmi == 18.5 || @compute_bmi < 24.9
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'AIP Yucca Breakfast Hash', media: 'https://www.edamam.com/web-img/82e/82eb86c293f28613b3e01450f621d854.jpg', calories: 1992, totalWeight: 976, ingredientLines: '["1 large yucca root (3-4 cups cooked and diced)","1 lb ground beef","1.5 tsp dried thyme","2 tsp sea salt","1 tsp garlic powder","1 tsp onion powder","1/4 tsp ground cinnamon"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Asian Roasted Brussels Sprouts with Cranberries recipes', media: 'https://www.edamam.com/food-img/07e/07e106ab3536d57428e5c46d009038f8.jpg', calories: 655, totalWeight: 625, ingredientLines: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Pesto Orecchiette With Chicken Sausage Recipe', media: 'https://www.edamam.com/web-img/c9c/c9cb0cfcd309128bfe50c1edafd18de2.jpg', calories: 2584.7, totalWeight: 1088, ingredientLines: '["12 ounces orecchiette","1/2 pound green beans, trimmed and cut into 1-inch pieces","1 cup frozen peas","1 tablespoon olive oil","8 ounces fully cooked Italian-style chicken sausage links, thinly sliced","1/3 cup pesto","1/2 cup grated Parmesan (2 ounces)"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band alternating v-up', status: 'NOT STARTED', bodyPart: 'waist', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0969.gif', target: 'abs', workout_id: 969, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'assisted lying calves stretch', status: 'NOT STARTED', bodyPart: 'lower legs', equipment: 'assisted', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1708.gif', target: 'calves', workout_id: 1708, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate biceps curl (with arm blaster)', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/2403.gif', target: 'biceps', workout_id: 2403, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            elsif @compute_bmi == 25 || @compute_bmi < 29.9
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED',name: 'Corned Beef Breakfast Biscuits', media: 'https://www.edamam.com/web-img/4c5/4c5faca6ea3e09900c42f5b298a49ba1.jpg', calories: 2335, totalWeight: 985, ingredientLines: '["12 ounces Flakey biscuit dough ; - one can","2 tablespoon Oil","12 ounces Corned beef, canned ; - one can","1/2 cup Onion ; - chopped fine","2 cloves Garlic ; - finely diced","1 cup Shredded potatoes ; - frozen hash browns","1/2 teaspoon Black pepper ; - to taste","2 tablespoons ketchup ; - Garmish"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Luby\'s Macaroni and Cheese', media: 'https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg', calories: 1225, totalWeight: 616, ingredientLines: '["2 c dry elbow macaroni","2 Tbsp nonfat dry milk","2 Tbsp all pourpose flour","1 Tbsp butter or margarine, melted","1 1/4 c boiling water","3 c shredded yellow american cheese from the deli","1/4 tsp salt"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Sticky Honey Garlic Chicken', media: 'https://www.edamam.com/web-img/77d/77d0a5df76619d3ea06ad6f21ad39581.jpg', calories: 799.7, totalWeight: 341, ingredientLines: '["1 package frozen chicken tenders","1/3 c. honey","2 tbsp. soy sauce","4 cloves garlic, minced","2 tbsp. orange juice","Pinch salt, to taste","1 tsp. corn starch"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternating bicep curl with leg raised on exercise ball', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1649.gif', target: 'biceps', workout_id: 1649, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band single leg calf raise', status: 'NOT STARTED', bodyPart: 'lower legs', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0999.gif', target: 'calves', workout_id: 999, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate hammer preacher curl', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1646.gif', target: 'biceps', workout_id: 1646, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            elsif @compute_bmi == 30 || @compute_bmi < 34.9
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED',name: 'Corned Beef Breakfast Biscuits', media: 'https://www.edamam.com/web-img/4c5/4c5faca6ea3e09900c42f5b298a49ba1.jpg', calories: 2335, totalWeight: 985, ingredientLines: '["12 ounces Flakey biscuit dough ; - one can","2 tablespoon Oil","12 ounces Corned beef, canned ; - one can","1/2 cup Onion ; - chopped fine","2 cloves Garlic ; - finely diced","1 cup Shredded potatoes ; - frozen hash browns","1/2 teaspoon Black pepper ; - to taste","2 tablespoons ketchup ; - Garmish"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Asian Roasted Brussels Sprouts with Cranberries recipes', media: 'https://www.edamam.com/food-img/07e/07e106ab3536d57428e5c46d009038f8.jpg', calories: 655, totalWeight: 625, ingredientLines: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Chicken Sausage And Potato Skillet', media: 'https://www.edamam.com/web-img/9f5/9f5b4049981ffe777bd9b51ba6ee8fc5.jpg', calories: 2632.7, totalWeight: 1427, ingredientLines: '["2 small red potatoes, quartered","1 teaspoon olive oil","1 (3 oz) chicken sausage, sliced","1/2 yellow bell pepper, sliced","1/4 onion, sliced","1/4 teaspoon hot sauce","1 dash paprika"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band assisted pull-up', status: 'NOT STARTED', bodyPart: 'back', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0970.gif', target: 'lats', workout_id: 970, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band single leg reverse calf raise', status: 'NOT STARTED', bodyPart: 'lower legs', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1000.gif', target: 'calves', workout_id: 1000, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate preacher curl', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1647.gif', target: 'biceps', workout_id: 1647, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            elsif @compute_bmi == 35 || @compute_bmi < 39.9
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Philly Cheesesteak Chex Mix', media: '', calories: 2070, totalWeight: 764, ingredientLines: '["5 cups Wheat Chex® cereal","1 container (6 oz) French-fried onions","1/2 cup cubed provolone cheese","2 packages (3.25 oz each) beef jerky nuggets, cut in half","2 tablespoons cheese powder"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Luby\'s Macaroni and Cheese', media: 'https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg', calories: 1225, totalWeight: 616, ingredientLines: '["2 c dry elbow macaroni","2 Tbsp nonfat dry milk","2 Tbsp all pourpose flour","1 Tbsp butter or margarine, melted","1 1/4 c boiling water","3 c shredded yellow american cheese from the deli","1/4 tsp salt"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Quick Cajun Chicken Alfredo', media: 'https://www.edamam.com/web-img/49a/49a038b7dd9022e845b1ee930fb3b1d2.jpg', calories: 4763.7, totalWeight: 1830, ingredientLines: '["1 tablespoon(s) Smart Balance Butter","1 pound(s) boneless skinless chicken breasts cut into bite sized pieces","1 teaspoon(s) garlic powder","16 ounce(s) fettuccine cooked and drained","2 jar(s) Ragu cheesy classic alfredo sauce","2 dash(es) cajun seasoning or more if you like spicier"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band assisted wheel rollerout', status: 'NOT STARTED', bodyPart: 'waist', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0971.gif', target: 'abs', workout_id: 971, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'barbell floor calf raise', status: 'NOT STARTED', bodyPart: 'lower legs', equipment: 'barbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1370.gif', target: 'calves', workout_id: 1370, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate seated hammer curl', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1648.gif', target: 'biceps', workout_id: 1648, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            else
              @breakfast = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'AIP Yucca Breakfast Hash', media: 'https://www.edamam.com/web-img/82e/82eb86c293f28613b3e01450f621d854.jpg', calories: 1992, totalWeight: 976, ingredientLines: ["1 large yucca root (3-4 cups cooked and diced)","1 lb ground beef","1.5 tsp dried thyme","2 tsp sea salt","1 tsp garlic powder","1 tsp onion powder","1/4 tsp ground cinnamon"], startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @lunch = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Asian Roasted Brussels Sprouts with Cranberries recipes', media: 'https://www.edamam.com/food-img/07e/07e106ab3536d57428e5c46d009038f8.jpg', calories: 655, totalWeight: 625, ingredientLines: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @dinner = Food.create(diet_plan_id: @diet_plan.id, food_type: 'RECOMMENDED', name: 'Quick and Easy Sweet and Sticky Orange Chicken Glaze', media: 'https://www.edamam.com/web-img/321/321a9c66f53924267245b23dbc38b295.jpeg', calories: 1401.7, totalWeight: 745, ingredientLines: '["1 cup hoisin sauce","1 orange, zested","1/4 to 1/3 cup fresh orange juice","Hot chicken, for serving","1/4 cup toasted sesame seeds, for sprinkling"]', startDate: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, ingredients: '["1 pound Brussels sprouts, halved","1 tablespoon canola oil","2 tablespoons sugar","2 tablespoons water","1/2 cup dried cranberries","2 tablespoons fish sauce","1 teaspoon Asian chili-garlic sauce","1 teaspoon canola oil"]')
              @workout_plan_1 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band bench press', status: 'NOT STARTED', bodyPart: 'chest', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1254.gif', target: 'pectorals', workout_id: 1254, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_2 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'band close-grip push-up', status: 'NOT STARTED', bodyPart: 'upper arms', equipment: 'band', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0975.gif', target: 'triceps', workout_id: 975, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
              @workout_plan_3 = WorkoutPlan.create(user: current_user, workout_type: 'RECOMMENDED', name: 'dumbbell alternate side press', status: 'NOT STARTED', bodyPart: 'shoulders', equipment: 'dumbbell', gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0286.gif', target: 'delts', workout_id: 286, startDate: @client_profile.created_at + n.day, startDate_js: @client_profile.created_at + n.day, endDate: @client_profile.created_at + n.day, reps: 10, sets: 3)
            end

            n -= 1
          end

          render :create
        else
          head(:unprocessable_entity)
        end
      end

      def update
        @client_profile = ClientProfile.find(params[:id])

        if @client_profile.update(client_profile_params)
          render :update, status: :ok
        else
          render json: { errors: @client_profile.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def index
        @client_profile = ClientProfile.where(user: current_user)

        render json: { data: @client_profile }, status: :ok
      end

      private

      def client_profile_params
        params.require(:client_profile).permit(:first_name, :last_name, :height, :current_weight, :goal_weight, :sex, :age, :workout_frequency, :body_type, :target_date, :food_preference)
      end
    end
  end
end
